# Generated by Django 6.0 on 2025-12-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Адміністратор'), ('moderator', 'Модератор'), ('user', 'Користувач')], default='user', max_length=20, verbose_name='Роль'),
        ),
    ]
